import type { Locale } from '@/data/site';

export const quoteCopy = {
  en: {
    eyebrow: 'WORK ORDER / 01',
    title: 'Turn the constraint into a useful brief.',
    intro: 'Four short steps. Answers stay in this browser tab; nothing leaves it until you choose WhatsApp, email, or copy.',
    stepsLabel: 'Brief steps',
    steps: ['Service', 'Situation', 'Timeline & budget', 'Review & send'],
    done: 'completed',
    service: 'What kind of help do you need?',
    serviceHint: 'Fixed price, stated duration, and named deliverables. Diagnosis fees count toward an audit.',
    includes: 'You receive',
    situation: 'What is happening today?',
    situationHint: 'Share the symptom, the decision, or the product boundary. Leave out credentials and customer data.',
    timeline: 'What timing are you working with?',
    timelines: ['Flexible / exploring', 'Within 2–4 weeks', 'Urgent / incident-driven'],
    budget: 'How do you want to handle budget?',
    budgetHint: 'Prices are fixed. Choose the shape that fits; add context only if it changes the scope.',
    budgetContext: 'Anything else that shapes the scope? (optional)',
    identity: 'Who should I reply to? (optional)',
    identityHint: 'These lines travel only inside the message you send.',
    name: 'Name', company: 'Company', role: 'Role',
    review: 'Review the brief',
    counter: 'characters',
    back: 'Back',
    next: ['Continue → Situation', 'Continue → Timeline', 'Review brief'],
    startOver: 'Start over',
    missing: 'Some answers are missing.',
    fix: 'Go to the first missing step',
    errors: { serviceId: 'Choose one service.', situation: 'Describe the current situation.', timeline: 'Choose a timeline.', budgetMode: 'Choose how you want to handle budget.' },
    ledger: { title: 'BRIEF / LEDGER', service: 'Service', investment: 'Investment', duration: 'Duration', credit: 'Credit', timeline: 'Timeline', budget: 'Budget', edit: 'Edit', pending: '—', file: 'BRIEF.TXT' },
    handoff: {
      whatsapp: 'Send by WhatsApp', email: 'Send by email', copy: 'Copy brief', copied: 'Brief copied.', copyFailed: 'Copy was unavailable. Select the brief and copy it manually.',
      desktop: 'On desktop this opens WhatsApp Web.',
      privacy: 'Nothing is sent automatically. WhatsApp or email receive this brief only after you confirm there.',
      overLimit: 'This brief is longer than most email clients accept inside a link. Copy it and paste it into your message; the email button opens with the subject only.',
      whatsappLong: 'Long briefs may be trimmed by WhatsApp Web. Copy is the guaranteed path.',
      subject: 'Project brief for Erick González',
    },
    storage: 'Saved in this browser tab only; cleared when you start over or close the tab.',
  },
  es: {
    eyebrow: 'ORDEN DE TRABAJO / 01',
    title: 'Convierte la restricción en un resumen útil.',
    intro: 'Cuatro pasos breves. Las respuestas se quedan en esta pestaña; nada sale de ella hasta que elijas WhatsApp, correo o copiar.',
    stepsLabel: 'Pasos del resumen',
    steps: ['Servicio', 'Situación', 'Plazo y presupuesto', 'Revisar y enviar'],
    done: 'completado',
    service: '¿Qué tipo de ayuda necesitas?',
    serviceHint: 'Precio fijo, duración declarada y entregables con nombre. El diagnóstico se abona a la auditoría.',
    includes: 'Recibes',
    situation: '¿Qué está ocurriendo hoy?',
    situationHint: 'Comparte el síntoma, la decisión o el límite del producto. No incluyas credenciales ni datos de clientes.',
    timeline: '¿Con qué plazo estás trabajando?',
    timelines: ['Flexible / explorando', 'Dentro de 2–4 semanas', 'Urgente / motivado por incidente'],
    budget: '¿Cómo quieres manejar el presupuesto?',
    budgetHint: 'Los precios son fijos. Elige la forma que encaja; agrega contexto solo si cambia el alcance.',
    budgetContext: '¿Algo más que defina el alcance? (opcional)',
    identity: '¿A quién respondo? (opcional)',
    identityHint: 'Estas líneas viajan solo dentro del mensaje que envías.',
    name: 'Nombre', company: 'Empresa', role: 'Rol',
    review: 'Revisa el resumen',
    counter: 'caracteres',
    back: 'Atrás',
    next: ['Continuar → Situación', 'Continuar → Plazo', 'Revisar resumen'],
    startOver: 'Empezar de nuevo',
    missing: 'Faltan respuestas.',
    fix: 'Ir al primer paso pendiente',
    errors: { serviceId: 'Elige un servicio.', situation: 'Describe la situación actual.', timeline: 'Elige un plazo.', budgetMode: 'Elige cómo manejar el presupuesto.' },
    ledger: { title: 'RESUMEN / LEDGER', service: 'Servicio', investment: 'Inversión', duration: 'Duración', credit: 'Crédito', timeline: 'Plazo', budget: 'Presupuesto', edit: 'Editar', pending: '—', file: 'BRIEF.TXT' },
    handoff: {
      whatsapp: 'Enviar por WhatsApp', email: 'Enviar por correo', copy: 'Copiar resumen', copied: 'Resumen copiado.', copyFailed: 'No fue posible copiar. Selecciona el resumen y cópialo manualmente.',
      desktop: 'En escritorio abre WhatsApp Web.',
      privacy: 'Nada se envía automáticamente. WhatsApp o correo reciben este resumen sólo cuando confirmas el envío allí.',
      overLimit: 'Este resumen es más largo de lo que la mayoría de los clientes de correo aceptan dentro de un enlace. Cópialo y pégalo en tu mensaje; el botón de correo abre solo con el asunto.',
      whatsappLong: 'WhatsApp Web puede recortar resúmenes largos. Copiar es la vía garantizada.',
      subject: 'Resumen de proyecto para Erick González',
    },
    storage: 'Se guarda solo en esta pestaña del navegador; se borra al empezar de nuevo o al cerrarla.',
  },
} as const;

export type QuoteCopy = (typeof quoteCopy)[Locale];
