import type { Locale } from '@/data/site';

export const quoteCopy = {
  en: {
    kicker: 'PROJECT STARTER — 01',
    display: 'Brief.',
    intro: 'Two steps. Answers stay in this browser tab; nothing leaves it until you send.',
    stepsLabel: 'Brief steps',
    steps: ['Service & situation', 'Send'],
    current: 'current step',
    bandKicker: 'CHOOSE ONE',
    service: 'What kind of help do you need?',
    select: 'Select',
    selected: 'Selected',
    situation: 'What is happening today?',
    situationHint: 'The symptom, the decision, or the product boundary. Leave out credentials and customer data.',
    counter: 'characters',
    continue: 'Continue',
    sendKicker: 'STEP 02 / SEND',
    sendTitle: 'Your brief.',
    sendIntro: 'Timeline and budget start from honest defaults. Change them only if they do not fit.',
    serviceLabel: 'Service',
    changeService: 'Change service',
    timeline: 'Timeline',
    budget: 'Budget',
    context: 'Anything else that shapes the scope? (optional)',
    identityToggle: 'Add who to reply to',
    identityHint: 'Optional. These lines travel only inside the message you send.',
    name: 'Name', company: 'Company', role: 'Role',
    briefLabel: 'BRIEF.TXT',
    whatsapp: 'Send on WhatsApp', email: 'Send by email', copy: 'Copy brief', copied: 'Brief copied.', copyFailed: 'Copy was unavailable. Select the brief and copy it manually.',
    desktop: 'On desktop this opens WhatsApp Web.',
    privacy: 'Nothing is sent automatically. WhatsApp or email receive this brief only after you confirm there.',
    overLimit: 'This brief is longer than most email clients accept inside a link. Copy it and paste it into your message; the email button opens with the subject only.',
    whatsappLong: 'Long briefs may be trimmed by WhatsApp Web. Copy is the guaranteed path.',
    subject: 'Project brief for Erick González',
    startOver: 'Start over',
    storage: 'Saved in this browser tab only; cleared when you start over or close the tab.',
    errors: { serviceId: 'Choose one service.', situation: 'Describe the current situation.' },
    trust: [
      ['Fixed price', 'No hourly surprises. Scope stays explicit.'],
      ['Stated duration', 'Every service names its elapsed time.'],
      ['Diagnosis credit', 'Credited toward an audit booked within {days} days.'],
      ['Stays in this tab', 'Nothing is sent until you confirm in WhatsApp or email.'],
    ],
  },
  es: {
    kicker: 'INICIO DE PROYECTO — 01',
    display: 'Brief.',
    intro: 'Dos pasos. Las respuestas se quedan en esta pestaña; nada sale de ella hasta que envías.',
    stepsLabel: 'Pasos del resumen',
    steps: ['Servicio y situación', 'Enviar'],
    current: 'paso actual',
    bandKicker: 'ELIGE UNO',
    service: '¿Qué tipo de ayuda necesitas?',
    select: 'Elegir',
    selected: 'Elegido',
    situation: '¿Qué está ocurriendo hoy?',
    situationHint: 'El síntoma, la decisión o el límite del producto. No incluyas credenciales ni datos de clientes.',
    counter: 'caracteres',
    continue: 'Continuar',
    sendKicker: 'PASO 02 / ENVIAR',
    sendTitle: 'Tu resumen.',
    sendIntro: 'Plazo y presupuesto parten de valores honestos. Cámbialos solo si no encajan.',
    serviceLabel: 'Servicio',
    changeService: 'Cambiar servicio',
    timeline: 'Plazo',
    budget: 'Presupuesto',
    context: '¿Algo más que defina el alcance? (opcional)',
    identityToggle: 'Agregar a quién respondo',
    identityHint: 'Opcional. Estas líneas viajan solo dentro del mensaje que envías.',
    name: 'Nombre', company: 'Empresa', role: 'Rol',
    briefLabel: 'BRIEF.TXT',
    whatsapp: 'Enviar por WhatsApp', email: 'Enviar por correo', copy: 'Copiar resumen', copied: 'Resumen copiado.', copyFailed: 'No fue posible copiar. Selecciona el resumen y cópialo manualmente.',
    desktop: 'En escritorio abre WhatsApp Web.',
    privacy: 'Nada se envía automáticamente. WhatsApp o correo reciben este resumen sólo cuando confirmas el envío allí.',
    overLimit: 'Este resumen es más largo de lo que la mayoría de los clientes de correo aceptan dentro de un enlace. Cópialo y pégalo en tu mensaje; el botón de correo abre solo con el asunto.',
    whatsappLong: 'WhatsApp Web puede recortar resúmenes largos. Copiar es la vía garantizada.',
    subject: 'Resumen de proyecto para Erick González',
    startOver: 'Empezar de nuevo',
    storage: 'Se guarda solo en esta pestaña del navegador; se borra al empezar de nuevo o al cerrarla.',
    errors: { serviceId: 'Elige un servicio.', situation: 'Describe la situación actual.' },
    trust: [
      ['Precio fijo', 'Sin sorpresas por hora. El alcance queda explícito.'],
      ['Duración declarada', 'Cada servicio nombra su tiempo de ejecución.'],
      ['Crédito del diagnóstico', 'Se descuenta de una auditoría contratada dentro de {days} días.'],
      ['Se queda en esta pestaña', 'Nada se envía hasta que confirmas en WhatsApp o correo.'],
    ],
  },
} as const;

export type QuoteCopy = (typeof quoteCopy)[Locale];
